### ISSUE TITLE
/usr/bin/ld: cannot find -lpictureflow

### ISSUE THREAD

**Issue by cefn** [ariya/pictureflow#1]
Thanks for your work on pictureflow, Ariya.

I'd like to build pictureflow to be able to replicate this online tutorial...
http://www.rkblog.rk.edu.pl/w/p/rendering-pdf-files-pyqt4-pypoppler-qt4/

...but I have hit a brick wall on the library building process to be able to construct the python bindings.

I've cd-ed into pictureflow-qt and run...

```
qmake-qt4 [qmake defaults to qt5 on my system I think, so qmake on its own throws an error about missing qwidget.h]
make [seems successful]
make install [tells me nothing needs to be done]
```

Then cd-ed into pyqt and run...
    python configure.py
    make

...but this fails with the following error...

```
g++ -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-O1 -shared  -Wl,-O1 -Wl,--version-script=pictureflow.exp -o pictureflow.so sippictureflowcmodule.o sippictureflowPictureFlow.o -L/home/cefn/Downloads/pictureflow/pictureflow-qt/pyqt -L/home/cefn/Downloads/pictureflow/pictureflow-qt/pyqt/lib -L/usr/lib -L/usr/X11R6/lib -lpictureflow -lQtCore -lQtGui
/usr/bin/ld: cannot find -lpictureflow
collect2: error: ld returned 1 exit status
make[1]: *** [pictureflow.so] Error 1
make[1]: Leaving directory `/home/cefn/Downloads/pictureflow/pictureflow-qt/pyqt/pictureflow'
make: *** [all] Error 2
```

...which is consistent with the fact that the earlier "make install" didn't do anything - I'd have expected that step to copy a pictureflow library into the system somewhere.

Any idea if this code can still be made to work with a modern system (I'm running Ubuntu 14.04) ? I expect what I'm doing is a novice mistake, but the instructions I'm following at...
http://www.rkblog.rk.edu.pl/w/p/pictureflow-listing-images-pyqt4/
...don't seem feasible any more. 

I have installed a whole bunch of sip and python-qt packages to try and eliminate build errors up until this point, but all from the repositories, so should be fairly easy to reverse if there's anything I can change. However, the -lpictureflow error seems to be related to something failing within the pictureflow build, so I'm stuck at that point.

**Comment by ariya** [comment]
This seems to related to the PictureFlow Python and not necessarily this C++ version.
